git config --global alias.cm "commit -v -m"
git config --global alias.co "checkout"
git config --global alias.cb "checkout -b"
git config --global alias.aa "add --all ."
git config --global alias.st "status"
git config --global alias.last "log -1 HEAD"
git config --global alias.df "diff"
git config --global alias.ba "branch -a"
git config --global alias.bd "branch -d"
git config --global alias.mnf "merge --no-ff"
git config --global alias.addtl "commit --amend -C HEAD"
git config --global alias.ri "rebase -i"
git config --global alias.fp "fetch -p"
git config --global alias.lg "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
git config --global alias.cmcount "rev-list --all --count"

